const ACTIVITY_HARVEST = 0;
const ACTIVITY_TRANSFER_ENERGY = 1;
const ACTIVITY_BUILD = 2;
const ACTIVITY_UPGRADE = 3;
const activityList = new Array(ACTIVITY_HARVEST, ACTIVITY_TRANSFER_ENERGY, ACTIVITY_BUILD, ACTIVITY_UPGRADE);

const TASK_NO_ENERGY = 0;
const TASK_FULL_ENERGY = 1;
const taskList = new Array(TASK_NO_ENERGY, TASK_FULL_ENERGY);

const ROLE_HARVESTER = 0;
const ROLE_BUILDER = 1;
const ROLE_UPGRADER = 2;
const roleList = new Array(ROLE_HARVESTER, ROLE_BUILDER, ROLE_UPGRADER);

const PATH_NO_ENERGY = "#ffaa00";
const PATH_FULL_ENERGY = "#ffffff";
const pathList = new Array(PATH_NO_ENERGY, PATH_FULL_ENERGY);


module.exports = {
    ACTIVITY_HARVEST: ACTIVITY_HARVEST,
    ACTIVITY_TRANSFER_ENERGY: ACTIVITY_TRANSFER_ENERGY,
    ACTIVITY_BUILD: ACTIVITY_BUILD,
    ACTIVITY_UPGRADE: ACTIVITY_UPGRADE,
    activityList: activityList,

    TASK_NO_ENERGY: TASK_NO_ENERGY,
    TASK_FULL_ENERGY: TASK_FULL_ENERGY,
    taskList: taskList,

    ROLE_HARVESTER: ROLE_HARVESTER,
    ROLE_BUILDER: ROLE_BUILDER,
    ROLE_UPGRADER: ROLE_UPGRADER,
    roleList: roleList,

    PATH_NO_ENERGY: PATH_NO_ENERGY,
    PATH_FULL_ENERGY: PATH_FULL_ENERGY,
    pathList: pathList,
}