const ACTIVITY_HARVEST = 0;
const ACTIVITY_TRANSFER_ENERGY = 1;
const ACTIVITY_BUILD = 2;
const ACTIVITY_UPGRADE = 3;
const activityList = new Array(ACTIVITY_HARVEST, ACTIVITY_TRANSFER_ENERGY, ACTIVITY_BUILD, ACTIVITY_UPGRADE);

const TASK_NO_ENERGY = 0;
const TASK_FULL_ENERGY = 1;
const TASK_NEW_ENERGY = 2;
const TASK_PATROL = 3;
const taskList = new Array(TASK_NO_ENERGY, TASK_FULL_ENERGY, TASK_NEW_ENERGY, TASK_PATROL);

const ROLE_HARVESTER = 0;
const ROLE_BUILDER = 1;
const ROLE_UPGRADER = 2;
const ROLE_PIONEER = 3;
const ROLE_SOLDIER = 4;
const roleList = new Array(ROLE_HARVESTER, ROLE_BUILDER, ROLE_UPGRADER, ROLE_PIONEER, ROLE_SOLDIER);

const PATH_NO_ENERGY = "#ffaa00";
const PATH_NEW_ENERGY = "#bfd8ee";
const PATH_PATROL = "#fd7878";
const PATH_FULL_ENERGY = "#ffffff";
const pathList = new Array(PATH_NO_ENERGY, PATH_FULL_ENERGY, PATH_NEW_ENERGY, PATH_PATROL);

const PATTERN_NONE = 0;
const PATTERN_JUST_TERRAIN = 1;
const PATTERN_CHECKER_BOARD = 2;
const patternList = new Array(PATTERN_NONE, PATTERN_JUST_TERRAIN, PATTERN_CHECKER_BOARD);

const OBSTACLE_OBJECT_TYPES_INANIMATE = ["spawn", "source", "mineral", "controller", "wall", "constructedWall", "extension", "link", "storage", "tower", "observer", "powerSpawn", "powerBank", "lab", "terminal", "nuker"];

module.exports = {
    ACTIVITY_TRANSFER_ENERGY: ACTIVITY_TRANSFER_ENERGY,
    ACTIVITY_HARVEST: ACTIVITY_HARVEST,
    ACTIVITY_UPGRADE: ACTIVITY_UPGRADE,
    ACTIVITY_BUILD: ACTIVITY_BUILD,
    activityList: activityList,

    TASK_FULL_ENERGY: TASK_FULL_ENERGY,
    TASK_NEW_ENERGY: TASK_NEW_ENERGY,
    TASK_NO_ENERGY: TASK_NO_ENERGY,
    TASK_PATROL: TASK_PATROL,
    taskList: taskList,

    ROLE_HARVESTER: ROLE_HARVESTER,
    ROLE_UPGRADER: ROLE_UPGRADER,
    ROLE_BUILDER: ROLE_BUILDER,
    ROLE_PIONEER: ROLE_PIONEER,
    ROLE_SOLDIER: ROLE_SOLDIER,
    roleList: roleList,

    PATH_FULL_ENERGY: PATH_FULL_ENERGY,
    PATH_NEW_ENERGY: PATH_NEW_ENERGY,
    PATH_NO_ENERGY: PATH_NO_ENERGY,
    PATH_PATROL: PATH_PATROL,
    pathList: pathList,

    PATTERN_CHECKER_BOARD: PATTERN_CHECKER_BOARD,
    PATTERN_JUST_TERRAIN: PATTERN_JUST_TERRAIN,
    PATTERN_NONE: PATTERN_NONE,
    patternList: patternList,

    OBSTACLE_OBJECT_TYPES_INANIMATE: OBSTACLE_OBJECT_TYPES_INANIMATE,
}