const ACTIVITY_HARVEST = 0;
const ACTIVITY_TRANSFER_ENERGY = 1;
const ACTIVITY_BUILD = 2;
const ACTIVITY_UPGRADE = 3;

const TASK_NO_ENERGY = 0;
const TASK_FULL_ENERGY = 1;

const ROLE_HARVESTER = 0;
const ROLE_BUILDER = 1;
const ROLE_UPGRADER = 2;

const PATH_NO_ENERGY = "#ffaa00";
const PATH_FULL_ENERGY = "#ffffff";

module.exports = {
    ACTIVITY_HARVEST: ACTIVITY_HARVEST,
    ACTIVITY_TRANSFER_ENERGY: ACTIVITY_TRANSFER_ENERGY,
    ACTIVITY_BUILD: ACTIVITY_BUILD,
    ACTIVITY_UPGRADE: ACTIVITY_UPGRADE,

    TASK_NO_ENERGY: TASK_NO_ENERGY,
    TASK_FULL_ENERGY: TASK_FULL_ENERGY,

    ROLE_HARVESTER: ROLE_HARVESTER,
    ROLE_BUILDER: ROLE_BUILDER,
    ROLE_UPGRADER: ROLE_UPGRADER,

    PATH_NO_ENERGY: PATH_NO_ENERGY,
    PATH_FULL_ENERGY: PATH_FULL_ENERGY,
}
